// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath 'com.google.gms:google-services:4.4.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Fix for plugins using deprecated 'proguard-android.txt' (e.g. background-geolocation)
subprojects {
    afterEvaluate { proj ->
        if (proj.hasProperty('android')) {
            proj.android.buildTypes.each { buildType ->
                def oldFile = proj.android.getDefaultProguardFile('proguard-android.txt')
                def newFile = proj.android.getDefaultProguardFile('proguard-android-optimize.txt')
                def files = buildType.proguardFiles
                if (files.contains(oldFile)) {
                    files.remove(oldFile)
                    files.add(newFile)
                }
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
