export enum RideState {
    IDLE = 'IDLE',
    TRACKING = 'TRACKING',
    MANUAL_PAUSE_MODAL = 'MANUAL_PAUSE_MODAL',
    PAUSED = 'PAUSED',
    AUTO_PAUSED = 'AUTO_PAUSED',
    STOP_CONFIRMATION = 'STOP_CONFIRMATION',
    RIDE_SUMMARY = 'RIDE_SUMMARY'
  }
  
  export type AutoPauseTrigger = 'MOVEMENT' | 'SIGNAL_LOST' | 'SIGNAL_RESTORED' | 'STATIONARY';
  