export enum RideState {
  IDLE = 'IDLE',
  TRACKING = 'TRACKING',
  MANUAL_PAUSE_MODAL = 'MANUAL_PAUSE_MODAL', // UI state
  PAUSED = 'PAUSED',
  AUTO_PAUSED = 'AUTO_PAUSED',
  AUTO_RESUME = 'AUTO_RESUME', // Transient state
  GPS_SIGNAL_LOST = 'GPS_SIGNAL_LOST',
  STOP_CONFIRMATION = 'STOP_CONFIRMATION',
  RIDE_SUMMARY = 'RIDE_SUMMARY'
}

export type AutoPauseTrigger = 'MOVEMENT' | 'SIGNAL_LOST' | 'SIGNAL_RESTORED' | 'STATIONARY' | 'BACKGROUND' | 'FOREGROUND';
